# ユーザがatlantis applyとコメントしたら、`apply中` のタグをつける
name: 'Atlantis'

# Pull requestのコメントが作成された際に起動する
on:
  issue_comment:
    types: [created]

jobs:
  job:
    name: 'label'
    runs-on: ubuntu-latest
    steps:
      - name: Check for "atlantis apply" comment
        id: check-comment
        uses: actions/github-script@v6
        with:
          script: |
            const apply_command = 'atlantis apply'
            
            const comment = context.payload.comment.body.toLowerCase();
            console.log(comment);

            if (comment.startsWith(apply_command)) {
              github.rest.issues.addLabels({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['applying :surfer:']
              })
            }
