# ユーザがatlantis applyとコメントしたら、`apply中` のタグをつける
name: 'Atlantis'

# Pull requestのコメントが作成された際に起動する
on:
  issue_comment:
    types: [created]

jobs:
  job:
    name: 'label'
    runs-on: ubuntu-latest
    steps:
      - name: Check for "atlantis apply" comment
        id: check-comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            console.log(comment)
            console.log(context.payload.pull_request)

            if (comment.includes('atlantis apply')) {
              github.rest.issues.addLabels({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['applying']
              })
            }
