# ユーザがatlantis applyとコメントしたら、`apply中` のタグをつける
name: 'Atlantis'

# Pull requestのコメントが作成された際に起動する
on:
  issue_comment:
    types: [created]

env:
  START_APPLYING_COMMENT: 'atlantis apply'

jobs:
  job:
    name: 'label'
    runs-on: ubuntu-latest
    steps:
      # 「terraform apply」とユーザーがコメントした場合
      - name: 'Start applying'
        if: github.event.comment.body == env.START_APPLYING_COMMENT
        uses: actions/github-script@v3
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['applying']
            })

