# ユーザがatlantis applyとコメントしたら、`apply中` のタグをつける
name: 'Atlantis'

# Pull requestのコメントが作成された際に起動する
on:
  issue_comment:
    types: [created]

jobs:
  job:
    name: 'label'
    runs-on: ubuntu-latest
    steps:
      - name: Check for "atlantis apply" comment
        id: check-comment
        uses: actions/github-script@v3
        with:
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            return { commentContainsApply: comment.includes('atlantis apply') };

      - name: 'Start applying'
        if: ${{ steps.check-comment.outputs.commentContainsApply }}
        uses: actions/github-script@v3
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['applying']
            })

