# ユーザがatlantis applyとコメントしたら、`apply中` のタグをつける
name: 'Atlantis'

# Pull requestのコメントが作成された際に起動する
on:
  issue_comment:
    types: [created]

env:
  START_APPLYING_COMMENT: 'atlantis apply'

jobs:
  job:
    name: 'label'
    runs-on: ubuntu-latest
    steps:
      # 「terraform apply」とユーザーがコメントした場合
      - name: 'Start applying'
        if: github.event.issue.state == 'open' && github.event.issue.pull_request != null && github.event.comment.body == env.START_APPLYING_COMMENT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr update ${{ github.event.pull_request.number }} --add-label "apply中"
